# Config file for SecretLife
# all messages use MiniMessage format !(https://docs.advntr.dev/minimessage/)
messages:
  # Completed messages
  completed-title: "<green><bold>âœ”</bold> You completed your secret task!"
  # Failed messages
  failed-title: "<dark_red><bold>âŒ</bold> You failed your secret task!"
  # Info messages
  info-chat: "<blue><bold>â“˜</bold> Info coming soon!"
  # Reroll messages
  reroll-title: "<dark_green>ğŸ” Rerolling..."
  # Command messages
  command-no-permission: "<red>âš  You do not have permission to use this command!"
  # Messages that are sent when the player respawns on a life
  player-respawn-2-lives: "<yellow>You have died, and are now on 2 lives!"
  player-respawn-1-life: "<red>You have died, and are now on 1 life!"
  player-respawn-no-lives: "<dark_red>You have died, and are out of SecretLife!"

items:
  totem-custom-model-data: 1
  secret-book-custom-model-data: 1

# Secrets, you can add as many as you want, and add {player} to choose a random player's name.
secrets:
  - "<green>test {player}"
  - "<yellow>test2 {player}"
  - "<gold>test{player}3"
reroll-secrets:
  - "<dark_green>test {player}"
  - "<dark_aqua>test2 {player}"
  - "<dark_red>test{player}3"

# File version (do NOT edit)
file-version: 1.5
