# Config file for SecretLife
# all messages use MiniMessage format !(https://docs.advntr.dev/minimessage/)
messages:
  # Completed messages
  completed-chat: "<green><bold>âœ”</bold> You clicked The Completed Button!"
  completed-title: "<green><bold>âœ”</bold> Completed"
  completed-subtitle: "<green>You clicked The Completed Button!"
  # Failed messages
  failed-chat: "<dark_red><bold>âŒ</bold> You clicked The Failed Button!"
  failed-title: "<dark_red><bold>âŒ</bold> Failed"
  failed-subtitle: "<dark_red>You clicked The Failed Button!"
  # Info messages
  info-chat: "<blue><bold>â“˜</bold> You clicked The Info Button!"
  info-title: "<blue><bold>â“˜</bold> Info"
  info-subtitle: "<blue>You clicked The Info Button!"
  # Reroll messages
  reroll-chat: "<dark_green>ğŸ” You clicked The Reroll Button!"
  reroll-title: "<dark_green>ğŸ” Reroll"
  reroll-subtitle: "<dark_green>You clicked The Reroll Button!"
  # Command messages
  command-no-permission: "<red>âš  You do not have permission to use this command!"
  # Messages that are sent when the player respawns on a life
  player-respawn-2-lives: "<yellow>You have died, and are now on 2 lives!"
  player-respawn-1-life: "<red>You have died, and are now on 1 life!"
  player-respawn-no-lives: "<dark_red>You have died, and are out of SecretLife!"

items:
  totem-custom-model-data: 1
  secret-book-custom-model-data: 1

# Secrets, you can add as many as you want, and add {player} to choose a random player's name.
secrets:
  - "<green>test {player}"
  - "<yellow>test2 {player}"
  - "<gold>test{player}3"

# File version (do NOT edit)
file-version: 1.4
