# Config file for SecretLife
# all messages use MiniMessage format !(https://docs.advntr.dev/minimessage/)
messages:
  # Completed message
  completed-title: "<green><bold>âœ”</bold> You completed your secret task!"
  # Failed message
  failed-title: "<dark_red><bold>âŒ</bold> You failed your secret task!"
  # Reroll message
  reroll-title: "<dark_green>ğŸ” Rerolling..."
  # Info message
  info-chat: "<blue><bold>â“˜</bold> Info coming soon!<br><gray>Edit this message in the config.yml file!"
  # Command messages
  command-no-permission: "<red>âš  You do not have permission to use this command!"
  # Messages that are sent when the player respawns on a life
  player-respawn-2-lives: "<yellow>You have died, and are now on 2 lives!"
  player-respawn-1-life: "<red>You have died, and are now on 1 life!"
  player-respawn-no-lives: "<dark_red>You have died, and are out of SecretLife!"

items:
  secret-totem-custom-model-data: 1
  reroll-secret-totem-custom-model-data: 2
  heart-totem-custom-model-data: 3
  secret-book-custom-model-data: 1
  reroll-secret-book-custom-model-data: 2

# Secrets, you can add as many as you want, and add {player} to choose a random player's name.
secrets:
  - "<green>Secret 1"
  - "<bold>{player}</bold> Secret 2"
reroll-secrets:
  - "<dark_green>Hard secret"
  - "<underlined>{player}</underlined> Hard Secret 2"

# File version (do NOT edit)
file-version: 1.0
